### ISSUE TITLE
Cannot Update Genetic Weights

### ISSUE THREAD

**Issue by gordon1470** [synkarius/saltbot#151]
When I click the "Update Genetic Weights" button on the latest repo, I get this error in the console, and nothing else happens:

Error in response to storage.get: ReferenceError: binaryInsertByProperty is not defined
    at Updater.getCharacter (chrome-extension://jfgdhipoabaocjmgcacggjgkanfbfmel/records.js:38:3)
    at Object.callback (chrome-extension://jfgdhipoabaocjmgcacggjgkanfbfmel/popup.js:286:27)
    at Simulator.evalMutations (chrome-extension://jfgdhipoabaocjmgcacggjgkanfbfmel/popup.js:199:23)
    at HTMLDivElement.<anonymous> (chrome-extension://jfgdhipoabaocjmgcacggjgkanfbfmel/popup.js:540:13)

The bot works fine otherwise, still bets normally.

**Comment by calexil** [comment]
try inspecting the element and check the log to see what it says

**Comment by gordon1470** [comment]
when I click the Update button, it shows the error I put into the message above in the console. I'll paste a screenshot of the window to make sure, but that's what comes up. https://puu.sh/w7gOM/379b079f4d.png

**Comment by reconman** [comment]
Thanks for the bug report. I wasn't sure if my last commit was ok to commit since I had tested some things but not everything. I've forgot to include a new Javascript file utils.js in the popup.html.

I also found out that my logging changes increased the calculation time of chromosomes at least hundredfold because the console was spammed with log messages.

Should be fixed now with my last commit.
