### ISSUE TITLE
Issue getting chromosomes started

### ISSUE THREAD

**Issue by jestrickling** [synkarius/saltbot#69]
I had things mostly good to go, then something stopped working. Tried reinstalling the extension and reinstalling chrome, but now, after whenever I try to update the genetic weights, I get the following error:

> Error in response to storage.get: TypeError: Cannot read property 'length' of undefined
>     at Object.callback (chrome-extension://bholoegapebhflljekancpcnajigaiih/popup.js:237:30)
>     at Simulator.evalMutations (chrome-extension://bholoegapebhflljekancpcnajigaiih/popup.js:162:23)
>     at HTMLDivElement.<anonymous> (chrome-extension://bholoegapebhflljekancpcnajigaiih/popup.js:479:13)handler @ extensions::uncaught_exception_handler:8exports.handle @ extensions::uncaught_exception_handler:100safeCallbackApply @ extensions::sendRequest:23handleResponse @ extensions::sendRequest:72

I've tried doing this with all other extensions disabled, and also with and without importing the provided records. I always click reset pool first. Same error keeps popping up.

**Comment by jestrickling** [comment]
Don't know what I did differently this time but it seems to be working now.
